{% set name = "lodash" %}
{% set version = "4.17.11" %}
{% set sha256 = "c9733b84673b1f646d28e9b1bdc06a97c36ba55ad18c71702ac8a8e2326f28cc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lodash/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g lodash
  requires:
    - nodejs
   

about:
  home: https://github.com/lodash/lodash
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A modern JavaScript utility library delivering modularity, performance, & extras.'
  description: |
    A modern JavaScript utility library delivering modularity, performance, & extras.  
  doc_url: https://lodash.com/docs
  dev_url: https://github.com/lodash/lodash

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
