{% set name = "lodash" %}
{% set version = "4.17.10" %}
{% set sha256 = "9f60d0db8727998fe59ff2ffc3af4853b7255d0b86262f844d997c2fd984cc90" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lodash/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g .

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g lodash
  requires:
    - nodejs
   

about:
  home: https://github.com/lodash/lodash
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A modern JavaScript utility library delivering modularity, performance, & extras.'
  description: |
    A modern JavaScript utility library delivering modularity, performance, & extras.  
  doc_url: https://lodash.com/docs
  dev_url: https://github.com/lodash/lodash

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
