travis:
  secure:
    BINSTAR_TOKEN: VL+WBgPKGgicXYBZb1T7uKWwCK75qMwm+jQCbm5cbel3QFoDVuGa9+Y419UEJHN0YveWfpv84O6eiz0JN5IcoJJOJRLkTeD+xXYKDS656rjn1ESHT0/1QWtKYLMQUWy8I9vIVgX5epKI+ATf4y4cOJnt7Rg5ipqnHtUgYlFWAP/dHUDDMV36zQKaJ+PRHk8WDC5CJlzC6fzMOYtTEKHkTMb0j+hZ3P0wUC9tK7cfLIGNBL2gVE/ddbSxpG+QnSUasU0eEvA+2GnvKHb9a6EFffrUrXmwbtfFyqwcnJTiGTCY53ykMuhIScBkWSAa/n2yBwHC6dhahG3QbFiAo96nrY9zOFGqtfoNJ7XtXT9IxpfMOyUb8dR1Pv6/9UYZymocSda8icha9y+WqzOPcAYVTf5NiULutrBNqgqr6D1RqH6X4b8OBTvNy222R906R8PUKZWpLt5AqK/eQ2tyOtQ99BOHHcKp21SGSkO27ToKx7Ee/xAsd5gxJklxV0wDGRoTYyGtRIzpepgXNvduqW4JWs+oBYSfi5LH45wNbWnFCFwaza+JYvUf6rd/X4YGDezlXvSvzY2i1OAo9q/aRKXc+GaUTTHBDriBP5oVJR96d4cFXJukV9wXRF7WmswTahVL9ea3B8Vpd4vchTHWj31nhwKPRO77Xyx1ZHpYtAY6YbQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
