travis:
  secure:
    BINSTAR_TOKEN: oTK8kWcpwULm+6TrRRnVHZ+diJU5DXJPHe0GexeYyz0rAbHvJco61mvPWPE0ZI8PYK98sIH5BpJIqRNEYSSM+W9IPwJAr8wDVzW7Ex5nPmOVrfLE1BXvbUgZodadSpLOsG434cDV9+H92/9nvm3w0P7VSP6C6BqqGoQiwQO6XKe6l+GwWtkZ+BgL7Lc8lWjuFB7OcQ4AYc/1yDMwsrSsOjoCWKKinZkirswBFLI7g07wuBQ5eEV5zm7mNTYPcEmv9Qvc6riBP0jAIGK/PPAVPEGEZ7a5KfhsIzigm/6WPK57lfYTC3YD8wbsxTeWebakQA/I1isirR0VRq3qXHNLBNV5e1S2cNiwc06KDby4gxAu1keUiLI5D0rqYioRJo8xc+4nK9L1y9MKGxsJa5VhyiY0YBX6zkub4nt5MEZwKzEq6O2mloTCLyTw2pFLIVPPB8aN8WFxwKIwVLPpfnO6EL35eh6tTYjRL2fOspssswchsG/DhsZ3k79zVgcD8MRS4vU/YwFIHY7FzpQ04IF2lAegYAe7T5FYDIapuOPExApfdsxyxJ+SgPAcwktFRl7smZSYWR3Ea04N63Bivouvo836haCuiZwMYz3bLOyhqBcv6Peu44q9iHQW8e/a2OK9jgepqRzpQyZ6InYzMYZLLeCFY4U/zqRw3q3eklsTNJo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
